//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billing()
        {
            this.Customers = new HashSet<Customer>();
            this.GeneralLedgers = new HashSet<GeneralLedger>();
            this.OnlineReceiptings = new HashSet<OnlineReceipting>();
        }
    
        public int BillId { get; set; }
        public int CustomerId { get; set; }
        public int MeterNo { get; set; }
        public string ReferenceId { get; set; }
        public System.DateTime ReadingDate { get; set; }
        public decimal PreviousReading { get; set; }
        public decimal CurrentReading { get; set; }
        public Nullable<decimal> UnitConsumed { get; set; }
        public decimal Rate { get; set; }
        public Nullable<decimal> CurrentBill { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> CreditApplied { get; set; }
        public decimal StdCharges { get; set; }
        public decimal TotalOutStanding { get; set; }
        public Nullable<System.DateTime> Duedate { get; set; }
        public int UserId { get; set; }
        public System.DateTime AuditdateTime { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralLedger> GeneralLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineReceipting> OnlineReceiptings { get; set; }
    }
}
