//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartsOfAccount
    {
        public int AccountId { get; set; }
        public int AccountNumber { get; set; }
        public byte[] AccountName { get; set; }
        public string AcountType { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public byte[] CreatedDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public string GLAccount { get; set; }
        public int UserId { get; set; }
    
        public virtual GeneralLedger GeneralLedger { get; set; }
        public virtual User User { get; set; }
    }
}
