//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public int IDNumber { get; set; }
        public string FirstName { get; set; }
        public string MidleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string County { get; set; }
        public string SubCounty { get; set; }
        public string Location { get; set; }
        public string Village { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int MeterNo { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public int AuditId { get; set; }
        public System.DateTime AuditDateTime { get; set; }
    
        public virtual Audit Audit { get; set; }
        public virtual Audit Audit1 { get; set; }
        public virtual Billing Billing { get; set; }
        public virtual Message Message { get; set; }
        public virtual Meter Meter { get; set; }
        public virtual OnlineReceipting OnlineReceipting { get; set; }
    }
}
