//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineReceipting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineReceipting()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int ReceiptId { get; set; }
        public int ReceiptNumber { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string PaymentMethod { get; set; }
        public decimal PaymentAmount { get; set; }
        public System.DateTime BillingPeriodStart { get; set; }
        public System.DateTime BillingPeriodEnd { get; set; }
        public int BillId { get; set; }
        public string Remarks { get; set; }
        public string ProcceessedBy { get; set; }
    
        public virtual Billing Billing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
