//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading
    {
        public int ReadingId { get; set; }
        public int MeterId { get; set; }
        public System.DateTime Readingdate { get; set; }
        public decimal MeterReading { get; set; }
        public int UserId { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
